# Generated by Django 3.2 on 2022-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabbageApp', '0003_popup_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('면적', models.IntegerField(blank=True, null=True)),
                ('생산량', models.IntegerField(blank=True, null=True)),
                ('물가지수', models.IntegerField(blank=True, null=True)),
                ('총지수전년동월비', models.IntegerField(blank=True, null=True)),
                ('신선식품지수전년동월비', models.IntegerField(blank=True, null=True)),
                ('평균기온', models.IntegerField(blank=True, null=True)),
                ('평균최고기온', models.IntegerField(blank=True, null=True)),
                ('평균최저기온', models.IntegerField(blank=True, null=True)),
                ('평균상대습도', models.IntegerField(blank=True, null=True)),
                ('평균풍속', models.IntegerField(blank=True, null=True)),
                ('월합강수량', models.IntegerField(blank=True, null=True)),
                ('총지수전년누계비', models.IntegerField(blank=True, null=True)),
                ('신선식품지수전년누계비', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Popup',
        ),
    ]
