# Generated by Django 3.2 on 2022-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CabbageApp', '0004_auto_20220405_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabbageBusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('지역', models.TextField(blank=True, null=True)),
                ('월', models.BigIntegerField(blank=True, null=True)),
                ('면적', models.BigIntegerField(blank=True, null=True)),
                ('생산량', models.FloatField(blank=True, null=True)),
                ('물가지수', models.FloatField(blank=True, null=True)),
                ('총지수전년동월비', models.FloatField(blank=True, null=True)),
                ('신선식품지수전년동월비', models.FloatField(blank=True, null=True)),
                ('평균기온', models.FloatField(blank=True, null=True)),
                ('평균최고기온', models.FloatField(blank=True, null=True)),
                ('평균최저기온', models.FloatField(blank=True, null=True)),
                ('평균풍속', models.FloatField(blank=True, null=True)),
                ('월합강수량', models.FloatField(blank=True, null=True)),
                ('평균상대습도', models.FloatField(blank=True, null=True)),
                ('총지수전년누계비', models.FloatField(blank=True, null=True)),
                ('신선식품지수전년누계비', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cabbage_busan',
                'managed': False,
            },
        ),
    ]
