# Generated by Django 4.0.3 on 2022-04-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CabbageApp', '0006_cab6_cab7_cab8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
