# Generated by Django 3.2 on 2022-03-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cabbage_table_alter_onion_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabbageMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('년', models.IntegerField(blank=True, null=True)),
                ('월', models.IntegerField(blank=True, null=True)),
                ('상_도매가격', models.FloatField(blank=True, null=True)),
                ('중_도매가격', models.FloatField(blank=True, null=True)),
                ('상중_도매가격', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cabbage_mean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OnionMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('년', models.IntegerField(blank=True, null=True)),
                ('월', models.IntegerField(blank=True, null=True)),
                ('상_도매가격', models.FloatField(blank=True, null=True)),
                ('중_도매가격', models.FloatField(blank=True, null=True)),
                ('상중_도매가격', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'onion_mean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PepperMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('년', models.IntegerField(blank=True, null=True)),
                ('월', models.IntegerField(blank=True, null=True)),
                ('상_도매가격', models.FloatField(blank=True, null=True)),
                ('중_도매가격', models.FloatField(blank=True, null=True)),
                ('상중_도매가격', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pepper_mean',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadishMean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('년', models.IntegerField(blank=True, null=True)),
                ('월', models.IntegerField(blank=True, null=True)),
                ('상_도매가격', models.FloatField(blank=True, null=True)),
                ('중_도매가격', models.FloatField(blank=True, null=True)),
                ('상중_도매가격', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'radish_mean',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='cabbage',
            table='cabbage',
        ),
        migrations.AlterModelTable(
            name='onion',
            table='onion',
        ),
        migrations.AlterModelTable(
            name='pepper',
            table='pepper',
        ),
        migrations.AlterModelTable(
            name='radish',
            table='radish',
        ),
    ]
